service: fyndiq-ongoing-note-sync

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: eu-north-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'kms:Decrypt'
      Resource:
        - {
            'Fn::Join':
              [
                '',
                [
                  'arn:aws:kms:${self:provider.region}:',
                  Ref: 'AWS::AccountId',
                  ':key/alias/aws/ssm',
                ],
              ],
          }

package:
  exclude:
    - config.*
    - README.md
    - index.js

functions:
  ongoal:
    handler: handler.handler
    events:
      - schedule: rate(10 minutes)
    environment:
      ACCOUNT: ongoal
      DESCRIPTION: Sync delivery notes from Fyndiq to Ongoing
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'ssm:GetParameters'
        Resource:
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/ongoal/fyndiq/*',
                  ],
                ],
            }
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/ongoal/ongoing/*',
                  ],
                ],
            }
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/ongoal/slack/*',
                  ],
                ],
            }

  novellia:
    handler: handler.handler
    events:
      - schedule: rate(10 minutes)
    environment:
      ACCOUNT: novellia
      DESCRIPTION: Sync delivery notes from Fyndiq to Ongoing
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'ssm:GetParameters'
        Resource:
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/novellia/fyndiq/*',
                  ],
                ],
            }
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/novellia/ongoing/*',
                  ],
                ],
            }
          - {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:ssm:${self:provider.region}:',
                    Ref: 'AWS::AccountId',
                    ':parameter/novellia/slack/*',
                  ],
                ],
            }
